plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = 'webflux'

include 'backend:bootstrap'
include 'backend:common'
include 'backend:exception'
include 'backend:domain'
include 'backend:application'
include 'backend:infrastructure'
include 'backend:api'
include 'backend:monitoring'

