plugins {
	id 'org.jetbrains.kotlin.jvm'
	id 'org.jlleitschuh.gradle.ktlint'
}

kotlin {
	jvmToolchain(21)
}

ktlint {
	version.set("1.8.0")
	verbose.set(true)
	outputToConsole.set(true)
	coloredOutput.set(true)

	reporters {
		reporter(org.jlleitschuh.gradle.ktlint.reporter.ReporterType.PLAIN)
	}
}

bootJar {
	enabled = false
}

jar {
	enabled = true
}

dependencies {
	compileOnly 'io.swagger.core.v3:swagger-annotations:2.2.22'
}
